In [11]:
import pandas as pd

In [12]:
import numpy as np

In [13]:
from sklearn import linear_model 

In [14]:
df = pd.read_csv("homeprices.csv")

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
area     5 non-null int64
price    5 non-null int64
dtypes: int64(2)
memory usage: 160.0 bytes


In [16]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [17]:
model = linear_model.LinearRegression()

In [18]:
model.fit(df[["area"]].values,df[["price"]].values)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
model.coef_

array([[135.78767123]])

In [20]:
model.intercept_

array([180616.43835616])

In [25]:
model.predict(np.array([[3300]]))

array([[628715.75342466]])

In [26]:
import pickle

In [27]:
with open("model_pickle","wb") as file:
    pickle.dump(model,file)

In [28]:
with open("model_pickle","rb") as file:
    pickledModel = pickle.load(file)

In [29]:
pickledModel

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
pickledModel.predict(np.array([[3300]]))

array([[628715.75342466]])

In [32]:
from sklearn.externals import joblib

In [33]:
joblib.dump(model,"model_pickle_using_joblib")

['model_pickle_using_joblib']

In [34]:
modelPickledUsingJoblib = joblib.load("model_pickle_using_joblib")

In [35]:
modelPickledUsingJoblib.predict(np.array([[3300]]))

array([[628715.75342466]])